name: Create github release

on:
  push:
    branches:
      - release/*

jobs:
  build:

    name: Build
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build:prod

  release:
    
    name: Create release
    needs: build
    if: success()
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ 12.x ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract version number
        shell: bash
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/heads/release/})"
        id: extract_version
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          release_name: v${{ steps.extract_version.outputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build for linux
        run: npm run electron:linux

      - name: Upload linux build
        id: upload-linux-build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/sticky-codes-${{ steps.extract_version.outputs.version }}.AppImage
          asset_name: sticky-codes-${{ steps.extract_version.outputs.version }}.AppImage
          asset_content_type: application/vnd.appimage
